services:
  banchonet:
    image: banchonet
    hostname: banchonet
    container_name: banchonet
    build:
      context: .
      dockerfile: BanchoNET/Dockerfile
      args:
        PP_PROVIDER: ${PP_PROVIDER:-rosu}
    ports:
      - ${SERVER_PORT}:5000
    env_file:
      - .env
    volumes:
      - banchonet-lazer-data:/data/lazer
      - ${DATA_PATH:-./data}:/app/files
    restart: unless-stopped
    networks:
      banchonet:
        aliases:
          - osu.${DOMAIN}
          - notify.${DOMAIN}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    image: osunovemo-web
    hostname: web
    container_name: web
    build:
      context: ./osunovemo-web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_OSU_API_BASE_URL: https://osu.${DOMAIN}/api/v2
        NEXT_PUBLIC_OSU_NOTIFICATION_ENDPOINT: ${NOTIFICATION_ENDPOINT:-}
    environment:
      OSU_API_BASE_URL: http://osu.${DOMAIN}:5000/api/v2
      OSU_OAUTH_CLIENT_ID: ${WEB_CLIENT_ID}
      OSU_OAUTH_CLIENT_SECRET: ${WEB_CLIENT_SECRET}
      OSU_AUTH_SECRET: ${WEB_AUTH_SECRET}
      OSU_AUTH_SCOPE: "public identify friends.read chat.read chat.write"
      OSU_NOTIFICATION_ENDPOINT: ${NOTIFICATION_ENDPOINT:-ws://notify.${DOMAIN}:5000/notify}
    ports:
      - ${WEB_PORT:-16728}:3000
    restart: unless-stopped
    networks:
      - banchonet
    depends_on:
      - banchonet

  postgres:
    image: postgres:17
    hostname: banchonet-db
    container_name: banchonet-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - banchonet-db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    networks:
      - banchonet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h localhost || exit 1"]
      interval: 2s
      timeout: 20s
      retries: 10

  redis:
    image: redis:8
    hostname: banchonet-redis
    container_name: banchonet-redis
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASS}
    restart: unless-stopped
    ports:
        - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - banchonet-redis-data:/data
    networks:
      - banchonet
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 10

networks:
  banchonet:
    name: banchonet

volumes:
  banchonet-lazer-data:
    driver: local
  banchonet-db-data:
    driver: local
  banchonet-redis-data:
    driver: local