// <auto-generated />
using System;
using BanchoNET.Core.Models.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace BanchoNET.Core.Migrations
{
    [DbContext(typeof(BanchoDbContext))]
    [Migration("20260802202805_AddAccountSettings")]
    partial class AddAccountSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BanchoNET.Core.Models.Auth.OAuthClient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AllowedScopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RedirectUri")
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Trusted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OAuthClients");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Auth.SessionVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SessionVerifications");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Db.BeatmapSearchRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Ar")
                        .HasColumnType("real");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArtistUnicode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Bpm")
                        .HasColumnType("real");

                    b.Property<int>("CirclesCount")
                        .HasColumnType("integer");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Cs")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Favorites")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("HitLength")
                        .HasColumnType("integer");

                    b.Property<float>("Hp")
                        .HasColumnType("real");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<bool>("Nsfw")
                        .HasColumnType("boolean");

                    b.Property<float>("Od")
                        .HasColumnType("real");

                    b.PrimitiveCollection<int[]>("OwnerIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("OwnerNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Plays")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RankedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', coalesce(\"Title\", '') || ' ' || coalesce(\"TitleUnicode\", '')), 'A') ||\r\nsetweight(to_tsvector('simple', coalesce(\"Artist\", '') || ' ' || coalesce(\"ArtistUnicode\", '')), 'B') ||\r\nsetweight(to_tsvector('simple', coalesce(\"CreatorName\", '')), 'C') ||\r\nsetweight(to_tsvector('simple', coalesce(\"OwnerNames\", '') || ' ' || coalesce(\"Version\", '') || ' ' || coalesce(\"Source\", '') || ' ' || coalesce(\"Tags\", '')), 'D')", true);

                    b.Property<int>("SetId")
                        .HasColumnType("integer");

                    b.Property<long>("SetPlays")
                        .HasColumnType("bigint");

                    b.Property<int>("SlidersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpinnersCount")
                        .HasColumnType("integer");

                    b.Property<float>("StarRating")
                        .HasColumnType("real");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleUnicode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalLength")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("OwnerIds");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OwnerIds"), "GIN");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SetId");

                    b.HasIndex("Mode", "Status", "GenreId", "LanguageId", "Nsfw");

                    b.HasIndex("Bpm", "Cs", "Ar", "Od", "Hp", "StarRating", "Plays", "Favorites", "Rating");

                    b.HasIndex("Title", "TitleUnicode", "Artist", "ArtistUnicode", "Version", "Source", "Tags", "CreatorName", "OwnerNames");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title", "TitleUnicode", "Artist", "ArtistUnicode", "Version", "Source", "Tags", "CreatorName", "OwnerNames"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title", "TitleUnicode", "Artist", "ArtistUnicode", "Version", "Source", "Tags", "CreatorName", "OwnerNames"), new[] { "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops" });

                    b.ToTable("BeatmapSearch", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapCollaborator", b =>
                {
                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("character varying(32)");

                    b.HasKey("BeatmapId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("BeatmapCollaborators");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Ar")
                        .HasColumnType("numeric(4,2)");

                    b.Property<float>("Bpm")
                        .HasColumnType("numeric(15,3)");

                    b.Property<int>("CirclesCount")
                        .HasColumnType("integer");

                    b.Property<float>("Cs")
                        .HasColumnType("numeric(4,2)");

                    b.PrimitiveCollection<int[]>("Exits")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Fails")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("HitLength")
                        .HasColumnType("integer");

                    b.Property<float>("Hp")
                        .HasColumnType("numeric(4,2)");

                    b.Property<bool>("IsScoreable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MD5")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<string>("MaximumStatistics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<float>("Od")
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Passes")
                        .HasColumnType("bigint");

                    b.Property<long>("Plays")
                        .HasColumnType("bigint");

                    b.Property<int>("SetId")
                        .HasColumnType("integer");

                    b.Property<long>("SkillsId")
                        .HasColumnType("bigint");

                    b.Property<int>("SlidersCount")
                        .HasColumnType("integer");

                    b.Property<int>("SpinnersCount")
                        .HasColumnType("integer");

                    b.Property<float>("StarRating")
                        .HasColumnType("numeric(9,3)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("TotalLength")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("MD5")
                        .IsUnique();

                    b.HasIndex("Mode");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Plays");

                    b.HasIndex("SetId");

                    b.HasIndex("Status");

                    b.ToTable("Beatmaps", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapPlays", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer");

                    b.Property<int>("Plays")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "BeatmapId");

                    b.HasIndex("BeatmapId");

                    b.HasIndex("Plays");

                    b.ToTable("BeatmapPlays");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ArtistUnicode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)");

                    b.Property<float>("Bpm")
                        .HasColumnType("real");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(131072)
                        .IsUnicode(true)
                        .HasColumnType("character varying(131072)")
                        .HasDefaultValue("");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrivateUpload")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRankedOfficially")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScoreable")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Nsfw")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RankedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Rating")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("real")
                        .HasComputedColumnSql("COALESCE((\r\n    \"Ratings\"[1] * 1 + \"Ratings\"[2] * 2 + \"Ratings\"[3] * 3 + \"Ratings\"[4] * 4 +\r\n    \"Ratings\"[5] * 5 + \"Ratings\"[6] * 6 + \"Ratings\"[7] * 7 + \"Ratings\"[8] * 8 +\r\n    \"Ratings\"[9] * 9 + \"Ratings\"[10] * 10\r\n)::real / NULLIF(\r\n    \"Ratings\"[1] + \"Ratings\"[2] + \"Ratings\"[3] + \"Ratings\"[4] + \"Ratings\"[5] +\r\n    \"Ratings\"[6] + \"Ratings\"[7] + \"Ratings\"[8] + \"Ratings\"[9] + \"Ratings\"[10]\r\n, 0), 0)", true);

                    b.PrimitiveCollection<int[]>("Ratings")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<bool>("Storyboard")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)")
                        .HasDefaultValue("");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TitleUnicode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Video")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Id");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("PlayCount");

                    b.HasIndex("RankedDate");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("Beatmapsets", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetFavorite", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FavoriteAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PlayerId", "BeatmapsetId");

                    b.HasIndex("BeatmapsetId");

                    b.HasIndex("FavoriteAt");

                    b.ToTable("BeatmapsetFavorites");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ChannelDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoJoin")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("ReadPrivileges")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WritePrivileges")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ChannelPlayer", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("LastReadMessageId");

                    b.ToTable("ChannelPlayers");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ClientHashesDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adapters")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<string>("DiskSerial")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<DateTime>("LatestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OsuPath")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Uninstall")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("ClientHashes");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.CommentDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditedById")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MessageHtml")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<int>("RepliesCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ReplyToId")
                        .HasColumnType("bigint");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VotesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EditedById");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("VotesCount");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.CommentVote", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.LoginDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OsuVersion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseStream")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerLogins");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MessageDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAction")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerEventDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.HasIndex("MatchId", "Id");

                    b.ToTable("MultiplayerEvents", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerGameDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aborted")
                        .HasColumnType("boolean");

                    b.Property<int?>("BeatmapId")
                        .HasColumnType("integer");

                    b.Property<string>("BeatmapMD5")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<string>("BeatmapName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ForceCompleted")
                        .HasColumnType("boolean");

                    b.Property<short>("LobbyType")
                        .HasColumnType("smallint");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<int>("Mods")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("WinCondition")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MultiplayerGames", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerMatchDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HostId")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("StartTime");

                    b.ToTable("MultiplayerMatches", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerParticipantDto", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "MatchId");

                    b.HasIndex("MatchId");

                    b.ToTable("MultiplayerParticipants", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerScoreDto", b =>
                {
                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<float>("Accuracy")
                        .HasColumnType("numeric(6,3)");

                    b.Property<int>("Count100")
                        .HasColumnType("integer");

                    b.Property<int>("Count300")
                        .HasColumnType("integer");

                    b.Property<int>("Count50")
                        .HasColumnType("integer");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<int>("Gekis")
                        .HasColumnType("integer");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint");

                    b.Property<int>("Katus")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<int>("Misses")
                        .HasColumnType("integer");

                    b.Property<int>("Mods")
                        .HasColumnType("integer");

                    b.Property<long?>("ScoreId")
                        .HasColumnType("bigint");

                    b.Property<short>("Team")
                        .HasColumnType("smallint");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ScoreId");

                    b.ToTable("MultiplayerScores", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("CHAR");

                    b.Property<string>("AvatarExtension")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("AvatarUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AwayMessage")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(2)");

                    b.Property<string>("CoverFile")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("CoverPresetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CoverUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(false)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("HasSupported")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideOnlineActivity")
                        .HasColumnType("boolean");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(60)");

                    b.Property<byte>("PlayStyle")
                        .HasColumnType("smallint");

                    b.Property<bool>("PmFriendsOnly")
                        .HasColumnType("boolean");

                    b.Property<byte>("PreferredMode")
                        .HasColumnType("smallint");

                    b.Property<int>("Privileges")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RemainingSilence")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RemainingSupporter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("SkillsId")
                        .HasColumnType("bigint");

                    b.Property<byte>("SupporterLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TopPlaysCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserDiscord")
                        .HasMaxLength(37)
                        .HasColumnType("character varying(37)");

                    b.Property<string>("UserFrom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserInterests")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("UserNotify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("UserOcc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserPageContent")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("UserSig")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("UserTwitter")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserWebsite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("Country");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.HasIndex("Privileges");

                    b.HasIndex("SafeName")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerHistoryDto", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<short>("Metric")
                        .HasColumnType("smallint");

                    b.Property<short>("Granularity")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("PlayerId", "Mode", "Metric", "Granularity", "Date");

                    b.HasIndex("Date");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Date"), "brin");

                    b.ToTable("PlayerHistories", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerNotificationOptionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Name")
                        .IsUnique();

                    b.ToTable("PlayerNotificationOptions", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerProfileCustomizationDto", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("BeatmapsetDownload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("All");

                    b.Property<bool>("BeatmapsetShowAnimeCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("BeatmapsetShowNsfw")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("BeatmapsetTitleShowOriginal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ExtrasOrder")
                        .HasColumnType("jsonb");

                    b.Property<int?>("ProfileHue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerProfileCustomizations", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.RelationshipDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("Relation")
                        .HasColumnType("smallint");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("PlayerId", "TargetId", "Relation")
                        .IsUnique();

                    b.ToTable("Relationships", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ReleaseDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Prerelease")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SHA1")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Type");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ReplayWatches", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ScoreId");

                    b.HasIndex("Count");

                    b.HasIndex("ScoreId");

                    b.ToTable("ReplayWatches");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ScoreDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Acc")
                        .HasColumnType("numeric(6,3)");

                    b.Property<string>("BeatmapMD5")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<int>("ClientFlags")
                        .HasColumnType("integer");

                    b.Property<byte>("Grade")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasReplay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerfectCombo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("LazerMods")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("LegacyPerfect")
                        .HasColumnType("boolean");

                    b.Property<long>("LegacyTotalScore")
                        .HasColumnType("bigint");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<string>("ModKeys")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<int>("Mods")
                        .HasColumnType("integer");

                    b.Property<string>("OnlineChecksum")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<float>("PP")
                        .HasColumnType("numeric(7,3)");

                    b.Property<DateTimeOffset>("PlayTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Preserve")
                        .HasColumnType("boolean");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ranked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Statistics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("TimeElapsed")
                        .HasColumnType("integer");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScoreWithoutMods")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapMD5");

                    b.HasIndex("LegacyTotalScore");

                    b.HasIndex("MapId");

                    b.HasIndex("ModKeys");

                    b.HasIndex("Mode");

                    b.HasIndex("Mods");

                    b.HasIndex("OnlineChecksum");

                    b.HasIndex("PP");

                    b.HasIndex("PlayTime");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Ranked");

                    b.HasIndex("Status");

                    b.ToTable("Scores", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.SkillsDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BeatmapId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapId")
                        .IsUnique();

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Skills", null, t =>
                        {
                            t.HasCheckConstraint("CK_Skills_ExactlyOneOwner", "(\"PlayerId\" IS NOT NULL AND \"BeatmapId\" IS NULL) OR (\"PlayerId\" IS NULL AND \"BeatmapId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.StatsDto", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<int>("ACount")
                        .HasColumnType("integer");

                    b.Property<float>("Accuracy")
                        .HasColumnType("numeric(6,3)");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<int>("PP")
                        .HasColumnType("integer");

                    b.Property<int>("PeakRank")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PeakRankDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlayTime")
                        .HasColumnType("integer");

                    b.Property<long>("RankedScore")
                        .HasColumnType("bigint");

                    b.Property<int>("ReplayViews")
                        .HasColumnType("integer");

                    b.Property<int>("SCount")
                        .HasColumnType("integer");

                    b.Property<int>("SHCount")
                        .HasColumnType("integer");

                    b.Property<long>("Total100s")
                        .HasColumnType("bigint");

                    b.Property<long>("Total300s")
                        .HasColumnType("bigint");

                    b.Property<long>("Total50s")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalGekis")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalKatus")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.Property<int>("XCount")
                        .HasColumnType("integer");

                    b.Property<int>("XHCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "Mode");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ThreadDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapsetId")
                        .IsUnique();

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ThreadFollows", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ThreadId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ThreadFollows");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapCollaborator", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapDto", "Beatmap")
                        .WithMany("Collaborators")
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmap");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapsetDto", "Beatmapset")
                        .WithMany("Beatmaps")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmapset");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapPlays", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapDto", "Beatmap")
                        .WithMany("PlaysData")
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("PlayedBeatmaps")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmap");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Creator")
                        .WithMany("Beatmapsets")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetFavorite", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapsetDto", "Beatmapset")
                        .WithMany("BeatmapsetFavorites")
                        .HasForeignKey("BeatmapsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("FavoriteBeatmapsets")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmapset");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ChannelPlayer", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.ChannelDto", "Channel")
                        .WithMany("ChannelPlayers")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("PlayerChannels")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ClientHashesDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("ClientHashes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.CommentDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Editor")
                        .WithMany()
                        .HasForeignKey("EditedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BanchoNET.Core.Models.Dtos.CommentDto", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BanchoNET.Core.Models.Dtos.ThreadDto", "Thread")
                        .WithMany("Comments")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Editor");

                    b.Navigation("ReplyTo");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.CommentVote", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.CommentDto", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("CommentVotes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.LoginDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("LoginsData")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MessageDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.ChannelDto", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerEventDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.MultiplayerGameDto", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BanchoNET.Core.Models.Dtos.MultiplayerMatchDto", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerGameDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.MultiplayerMatchDto", "Match")
                        .WithMany("Games")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerMatchDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerParticipantDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.MultiplayerMatchDto", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerScoreDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.MultiplayerGameDto", "Game")
                        .WithMany("Scores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.ScoreDto", null)
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerHistoryDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerNotificationOptionDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("NotificationOptions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerProfileCustomizationDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithOne("ProfileCustomization")
                        .HasForeignKey("BanchoNET.Core.Models.Dtos.PlayerProfileCustomizationDto", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.RelationshipDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("Relationships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Target")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ReplayWatches", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("WatchedReplays")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.ScoreDto", "Score")
                        .WithMany("ReplayWatches")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ScoreDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapDto", "Beatmap")
                        .WithMany("Scores")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmap");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.SkillsDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapDto", "Beatmap")
                        .WithOne("Skills")
                        .HasForeignKey("BanchoNET.Core.Models.Dtos.SkillsDto", "BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithOne("Skills")
                        .HasForeignKey("BanchoNET.Core.Models.Dtos.SkillsDto", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Beatmap");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.StatsDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ThreadDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapsetDto", "Beatmapset")
                        .WithOne("Thread")
                        .HasForeignKey("BanchoNET.Core.Models.Dtos.ThreadDto", "BeatmapsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmapset");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ThreadFollows", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("ThreadFollows")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.ThreadDto", "Thread")
                        .WithMany("Follows")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapDto", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("PlaysData");

                    b.Navigation("Scores");

                    b.Navigation("Skills")
                        .IsRequired();
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetDto", b =>
                {
                    b.Navigation("Beatmaps");

                    b.Navigation("BeatmapsetFavorites");

                    b.Navigation("Thread")
                        .IsRequired();
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ChannelDto", b =>
                {
                    b.Navigation("ChannelPlayers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.CommentDto", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerGameDto", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MultiplayerMatchDto", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Games");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerDto", b =>
                {
                    b.Navigation("Beatmapsets");

                    b.Navigation("ClientHashes");

                    b.Navigation("CommentVotes");

                    b.Navigation("Comments");

                    b.Navigation("FavoriteBeatmapsets");

                    b.Navigation("IncomingRelationships");

                    b.Navigation("LoginsData");

                    b.Navigation("NotificationOptions");

                    b.Navigation("PlayedBeatmaps");

                    b.Navigation("PlayerChannels");

                    b.Navigation("ProfileCustomization");

                    b.Navigation("Relationships");

                    b.Navigation("Scores");

                    b.Navigation("SentMessages");

                    b.Navigation("Skills")
                        .IsRequired();

                    b.Navigation("Stats");

                    b.Navigation("ThreadFollows");

                    b.Navigation("WatchedReplays");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ScoreDto", b =>
                {
                    b.Navigation("ReplayWatches");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ThreadDto", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Follows");
                });
#pragma warning restore 612, 618
        }
    }
}
