// <auto-generated />
using System;
using BanchoNET.Core.Models.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BanchoNET.Core.Migrations
{
    [DbContext(typeof(BanchoDbContext))]
    partial class BanchoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BanchoNET.Core.Models.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Auth.SessionVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SessionVerifications");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapDto", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MapId"));

                    b.Property<float>("Ar")
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ArtistUnicode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("");

                    b.Property<float>("Bpm")
                        .HasColumnType("numeric(15,3)");

                    b.Property<int>("CirclesCount")
                        .HasColumnType("integer");

                    b.Property<long>("CoverId")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.Property<float>("Cs")
                        .HasColumnType("numeric(4,2)");

                    b.Property<bool>("Frozen")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasStoryboard")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVideo")
                        .HasColumnType("boolean");

                    b.Property<int>("HitLength")
                        .HasColumnType("integer");

                    b.Property<float>("Hp")
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("IgnoreHit")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRankedOfficially")
                        .HasColumnType("boolean");

                    b.Property<int>("LargeTickHit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MD5")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("CHAR(32)");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<float>("Od")
                        .HasColumnType("numeric(4,2)");

                    b.Property<long>("Passes")
                        .HasColumnType("bigint");

                    b.Property<long>("Plays")
                        .HasColumnType("bigint");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RankedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SetId")
                        .HasColumnType("integer");

                    b.Property<int>("SlidersCount")
                        .HasColumnType("integer");

                    b.Property<int>("SpinnersCount")
                        .HasColumnType("integer");

                    b.Property<float>("StarRating")
                        .HasColumnType("numeric(9,3)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TitleUnicode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("");

                    b.Property<int>("TotalLength")
                        .HasColumnType("integer");

                    b.HasKey("MapId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MD5")
                        .IsUnique();

                    b.HasIndex("MapId");

                    b.HasIndex("SetId");

                    b.ToTable("Beatmaps", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetDto", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SetId"));

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("SetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Beatmapsets", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ChannelDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoJoin")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("ReadPrivileges")
                        .HasColumnType("integer");

                    b.Property<int>("WritePrivileges")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ClientHashesDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adapters")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("CHAR");

                    b.Property<string>("DiskSerial")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("CHAR");

                    b.Property<DateTime>("LatestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OsuPath")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("CHAR");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Uninstall")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("CHAR");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("ClientHashes");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.LoginDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OsuVersion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseStream")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerLogins");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MessageDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Read");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("CHAR");

                    b.Property<string>("AwayMessage")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(2)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(false)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("HasSupported")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideOnlineActivity")
                        .HasColumnType("boolean");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(60)");

                    b.Property<byte>("PlayStyle")
                        .HasColumnType("smallint");

                    b.Property<bool>("PmFriendsOnly")
                        .HasColumnType("boolean");

                    b.Property<byte>("PreferredMode")
                        .HasColumnType("smallint");

                    b.Property<int>("Privileges")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RemainingSilence")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RemainingSupporter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.Property<byte>("SupporterLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("UserPageContent")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("Country");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.HasIndex("Privileges");

                    b.HasIndex("SafeName")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.RelationshipDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsMutual")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("Relation")
                        .HasColumnType("smallint");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Relation");

                    b.HasIndex("TargetId");

                    b.ToTable("Relationships", (string)null);
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ScoreDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Acc")
                        .HasColumnType("numeric(6,3)");

                    b.Property<string>("BeatmapMD5")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<int>("ClassicScore")
                        .HasColumnType("integer");

                    b.Property<int>("ClientFlags")
                        .HasColumnType("integer");

                    b.Property<int>("Count100")
                        .HasColumnType("integer");

                    b.Property<int>("Count300")
                        .HasColumnType("integer");

                    b.Property<int>("Count50")
                        .HasColumnType("integer");

                    b.Property<int>("Gekis")
                        .HasColumnType("integer");

                    b.Property<byte>("Grade")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasReplay")
                        .HasColumnType("boolean");

                    b.Property<int>("IgnoreHit")
                        .HasColumnType("integer");

                    b.Property<int>("IgnoreMiss")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPerfectCombo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean");

                    b.Property<int>("Katus")
                        .HasColumnType("integer");

                    b.Property<bool>("LegacyPerfect")
                        .HasColumnType("boolean");

                    b.Property<int>("LegacyTotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<int>("Misses")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<int>("Mods")
                        .HasColumnType("integer");

                    b.Property<string>("OnlineChecksum")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("CHAR(32)");

                    b.Property<float>("PP")
                        .HasColumnType("numeric(7,3)");

                    b.Property<DateTime>("PlayTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Preserve")
                        .HasColumnType("boolean");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ranked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("TimeElapsed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScoreWithoutMods")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapMD5");

                    b.HasIndex("LegacyTotalScore");

                    b.HasIndex("Mode");

                    b.HasIndex("Mods");

                    b.HasIndex("OnlineChecksum");

                    b.HasIndex("PP");

                    b.HasIndex("PlayTime");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Status");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.StatsDto", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<int>("ACount")
                        .HasColumnType("integer");

                    b.Property<float>("Accuracy")
                        .HasColumnType("numeric(6,3)");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<int>("PP")
                        .HasColumnType("integer");

                    b.Property<int>("PeakRank")
                        .HasColumnType("integer");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlayTime")
                        .HasColumnType("integer");

                    b.Property<long>("RankedScore")
                        .HasColumnType("bigint");

                    b.Property<int>("ReplayViews")
                        .HasColumnType("integer");

                    b.Property<int>("SCount")
                        .HasColumnType("integer");

                    b.Property<int>("SHCount")
                        .HasColumnType("integer");

                    b.Property<long>("Total100s")
                        .HasColumnType("bigint");

                    b.Property<long>("Total300s")
                        .HasColumnType("bigint");

                    b.Property<long>("Total50s")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalGekis")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalKatus")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalMisses")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.Property<int>("XCount")
                        .HasColumnType("integer");

                    b.Property<int>("XHCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "Mode");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Creator")
                        .WithMany("Beatmaps")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.BeatmapsetDto", "Beatmapset")
                        .WithMany("Beatmaps")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmapset");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Owner")
                        .WithMany("Beatmapsets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ClientHashesDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("ClientHashes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.LoginDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("LoginsData")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.MessageDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.RelationshipDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("Relationships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Target")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.ScoreDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.StatsDto", b =>
                {
                    b.HasOne("BanchoNET.Core.Models.Dtos.PlayerDto", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.BeatmapsetDto", b =>
                {
                    b.Navigation("Beatmaps");
                });

            modelBuilder.Entity("BanchoNET.Core.Models.Dtos.PlayerDto", b =>
                {
                    b.Navigation("Beatmaps");

                    b.Navigation("Beatmapsets");

                    b.Navigation("ClientHashes");

                    b.Navigation("IncomingRelationships");

                    b.Navigation("LoginsData");

                    b.Navigation("Relationships");

                    b.Navigation("Scores");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
